data:extend{
  {
    type = "int-setting",
    name = "gc-asif-ratio",
    setting_type = "startup",
    minimum_value = 25,
    maximum_value = 1000,
    default_value = 25,
    order = "b",
  },
  {
    type = "int-setting",
    name = "rc-asif-ratio",
    setting_type = "startup",
    minimum_value = 25,
    maximum_value = 1000,
    default_value = 25,
    order = "b",
  },
  {
    type = "int-setting",
    name = "bc-asif-ratio",
    setting_type = "startup",
    minimum_value = 25,
    maximum_value = 1000,
    default_value = 25,
    order = "b",
  },
  {
    type = "int-setting",
    name = "lds-asif-ratio",
    setting_type = "startup",
    minimum_value = 25,
    maximum_value = 1000,
    default_value = 25,
    order = "b",
  },
  {
    type = "int-setting",
    name = "eng-asif-ratio",
    setting_type = "startup",
    minimum_value = 25,
    maximum_value = 1000,
    default_value = 25,
    order = "b",
  },
  {
    type = "int-setting",
    name = "spd-3-asif-ratio",
    setting_type = "startup",
    minimum_value = 10,
    maximum_value = 100,
    default_value = 10,
    order = "c",
  },
  {
    type = "int-setting",
    name = "prod-3-asif-ratio",
    setting_type = "startup",
    minimum_value = 10,
    maximum_value = 100,
    default_value = 10,
    order = "c",
  },
--  {
--    type = "int-setting",
--    name = "pg-asif-ratio",
--    setting_type = "startup",
--    minimum_value = 25,
--    maximum_value = 1000,
--    default_value = 25,
--    order = "b",
--  },
}
