require("prototypes.entity.e-bulk-smelters")
--require("prototypes.recipe.r-bulk-smelters")
require("prototypes.recipe.r-bulk-smelters-oneshot")
require("prototypes.item.i-bulk-smelters")
require("prototypes.technology.t-bulk-smelters")